### ISSUE TITLE
Incorrect Sparse Depth Map

### ISSUE THREAD

**Issue by saimouli** [XYZ-qiyh/colmap_sparse_recon#1]
![00000000](https://user-images.githubusercontent.com/14081959/189014200-05e1e556-7d97-4e95-84a8-ee10e764dc01.jpg)
Though the sparse reconstruction results match as readme, Scan4 does not produce the same sparse depth as shown

**Comment by XYZ-qiyh** [comment]
Hello @saimouli 
I'll check it later and add the Google Drive link.

**Comment by XYZ-qiyh** [comment]
Hello, @saimouli 
1. The results of the sparse reconstruction is OK, you can run `python colmap_sparse_recon_posed.py` or using the results by NetDisk
2. The problem is converting the sparse points to sparse depth. After running `python colmap_sparse_to_depth.py`, you should get the sparse depth map for each image in `sparse_depth` folder. And the sparse depth map file should be saved as `pfm` file. The previous version has a bug of the output depth filename, which is currently fixed. You can refer to the diff of the changes.
3. Lastly, you can visualize the generated sparse depth map by running `python visualize_sparse.py`.

![rect_012_3_r5000](https://user-images.githubusercontent.com/45621782/189534505-8cadd76e-1988-4c95-ab99-403283b29f26.jpg)
